image: docker:19.03.13

stages:
  - build
  - deploy

variables:
  CLIENT_IMAGE_NAME: $CI_REGISTRY/scpomedialab/trajectories-of-engagement-client:$CI_COMMIT_REF_SLUG
  API_IMAGE_NAME: $CI_REGISTRY/scpomedialab/trajectories-of-engagement-api:$CI_COMMIT_REF_SLUG

build_client:
  stage: build
  script:
    - docker build -t $CLIENT_IMAGE_NAME -f ./client/Dockerfile ./client
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push $CLIENT_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
  tags:
    - proxy
  only:
    - main
    - staging
    - prod
    - tags


build_api:
  stage: build
  script:
    - docker build -t $API_IMAGE_NAME -f Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push $API_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
  tags:
    - proxy
  only:
    - main
    - staging
    - prod
    - tags

deploy:
  image:
    name: jrisp/kubehelper:latest
    entrypoint: [""]
  stage: deploy
  before_script:
    - export KUBECONFIG=$kubeconfig_file
  dependencies:
    - build_client
    - build_api
  script:
    - NS=trajectories-of-engagement
    - kubectl apply -f k8s/namespace.yml
    - cp ${MONGODB_SECRETS} k8s/overlays/$CI_COMMIT_REF_SLUG/mongodb.env
    - kubectl apply -k k8s/overlays/$CI_COMMIT_REF_SLUG
    - kubectl -n ${NS} rollout restart deployment ${NS}-api
    - kubectl -n ${NS} rollout restart deployment ${NS}-client
  environment:
    name: $CI_COMMIT_REF_SLUG
  tags:
    - proxy
  only:
   - prod
