apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trajectories-of-engagement

namePrefix: trajectories-of-engagement-

bases:
  - ../../base/

resources:
  - ingress.yml

commonLabels:
  stage: development

secretGenerator:
- name: mongodb
  literals:
    - database=trajectories-of-engagement
    - root_password=password
    - root_username=admin

images:
  - name: scpomedialab/trajectories-of-engagement-client
    newTag: 'master'
  - name: scpomedialab/trajectories-of-engagement-api
    newTag: 'master'
  - name: mongo
    newTag: '4.2'
