apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
  template:
    metadata:
      labels:
        component: db
    spec:
      containers:
        - name: db
          image: mongo:latest
          env:
            - name: MONGO_INITDB_DATABASE
              value: 'admin'
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: root_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: root_password
          volumeMounts:
            - name: db-vol
              mountPath: /data/db
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-pvc
