apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: scpomedialab/trajectories-of-engagement-client:latest
          env:
            - name: API_HOST
              value: trajectories-of-engagement-api.trajectories-of-engagement.svc.cluster.local
            - name: API_PORT
              value: '4000'
          imagePullPolicy: Always
