apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trajectories-of-engagement

namePrefix: trajectories-of-engagement-

bases:
  - ../../base/

resources:
  - ingress.yml

commonLabels:
  stage: staging

secretGenerator:
- name: mongodb
  env: mongodb.env

images:
  - name: scpomedialab/trajectories-of-engagement-client
    newTag: 'staging'
  - name: scpomedialab/trajectories-of-engagement-api
    newTag: 'staging'
  - name: mongo
    newTag: '4.2'
